const data = {
  0: {
    id: 0,
    title: "Сэндвич с ростбифом",
    cost: 230,
    description:
      "Хлеб тостовый, соус тартар, салат айсберг, ростбиф, томаты, огурцы",
    type: "Сэндвичи",
    img: "https://pitstopslv.ru/images/products/0.jpg",
  },
  1: {
    id: 1,
    title: "Чебурек с говяжьим фаршем",
    cost: 65,
    description: "с говяжьим фаршем",
    weight: 200,
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/1.jpg",
  },
  2: {
    id: 2,
    title: "Чебурек со свино-говяжьим фаршем",
    cost: 65,
    description: "со смешанным фаршем из свинины и говядины",
    weight: 200,
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/2.jpg",
  },
  3: {
    id: 3,
    title: "Беляш с говяжьим фаршем",
    cost: 65,
    description: "жареный с говяжьим фаршем",
    weight: 230,
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/3.jpg",
  },
  4: {
    id: 4,
    title: "Сосиска в тесте с картошкой",
    cost: 54,
    description: " обжаренная в дрожжевом тесте",
    weight: 265,
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/4.jpg",
  },
  5: {
    id: 5,
    title: "Сосиска в тесте с картошкой",
    cost: 69,
    description:
      " обжаренная в дрожжевой тесте, с добавлением по желанию клиента кетчупа, майонеза, горчицы, и двух или одного салата морковча, капуста (по телефону)",
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/5.jpg",
  },
  6: {
    id: 6,
    title: "Пирожок",
    cost: 30,
    description: "жаренный на дрожжевом тесте",
    weight: 180,
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/6.jpg",
    properties: {
      1: {
        name: "с капустой",
        cost: "30",
        weight: "180",
      },
      2: {
        name: "с картошкой",
        cost: "27",
        weight: "180",
      },
    },
  },
  7: {
    id: 7,
    title: "Вак Беляш",
    cost: 65,
    description: " с рубленным картофелем и добавлением говяжьего фарша",
    weight: 320,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/7.jpg",
  },
  8: {
    id: 8,
    title: "Тюльпин",
    cost: 69,
    description: "Кусочки куриной грудки с сыром, испеченные в песочном тесте",
    weight: 220,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/8.jpg",
  },
  9: {
    id: 9,
    title: "Самса с рубленной говядиной",
    cost: 72,
    description:
      " с кусочками рубленной говядины, луком, испеченная в слоеном тесте с кунжутом",
    weight: 170,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/9.jpg",
  },
  10: {
    id: 10,
    title: "Курник",
    cost: 65,
    description:
      "Кусочки курицы, с рубленным картофелем запечены в песочном тесте",
    weight: 280,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/10.jpg",
  },
  11: {
    id: 11,
    title: "Курник Большой",
    cost: 105,
    description:
      "Кусочки курицы, рубленный картофель, запечены в песочном тесте",
    weight: 480,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/11.jpg",
  },
  12: {
    id: 12,
    title: "Сосиска в тесте печеная",
    cost: 47,
    description: "Запеченая сосиска в слоеном тесте",
    weight: 90,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/12.jpg",
  },
  13: {
    id: 13,
    title: "Ватрушка с творогом",
    cost: 34,
    description: "Творог с сахаром, запеченый на дрожжевом тесте",
    weight: 125,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/13.jpg",
  },
  14: {
    id: 14,
    title: "Слойка с ветчиной и сыром",
    cost: 43,
    description: "Ветчина и сыр запеченый в слоеном тесте",
    weight: 80,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/14.jpg",
  },
  15: {
    id: 15,
    title: "Слойка с яблоком",
    cost: 43,
    description: "Яблочный джем, запеченый в слоеном тесте",
    weight: 80,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/15.jpg",
  },
  16: {
    id: 16,
    title: "Бутерброд с копченой колбасой и сыром",
    cost: 39,
    description: "Тертый сыр с колбасой запеченый на булочке",
    weight: 80,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/16.jpg",
  },
  17: {
    id: 17,
    title: "Хачапури",
    cost: 64,
    description: "Лодочка запеченая с творогом,сыром, и яйцом",
    weight: 210,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/17.jpg",
  },
  18: {
    id: 18,
    title: "Батон",
    cost: 25,
    description: "Батон",
    weight: 450,
    type: "Хлеб",
    img: "https://pitstopslv.ru/images/products/18.jpg",
  },
  19: {
    id: 19,
    title: "Салат с капустой",
    cost: 32,
    description:
      "Салат из свежей капусты, с добавление укроп, и рубленной моркови",
    weight: 100,
    type: "Салаты",
    img: "https://pitstopslv.ru/images/products/19.jpg",
  },
  20: {
    id: 20,
    title: "Морковь по корейски Морковча",
    cost: 32,
    description:
      "Салат из свежей рубленной моркови с добавлением чеснока, масла, и приправ",
    weight: 100,
    type: "Салаты",
    img: "https://pitstopslv.ru/images/products/20.jpg",
  },
  21: {
    id: 21,
    title: "Шаурма в Блине с Курицей",
    cost: 125,
    description:
      "Шаурма завернутая в блин, с обжаренной на угольной печи куриной грудкой, овощным салатом(огурец,помидор,лук) и фирменными белым и красным соусами",
    weight: 310,
    type: "Шаурма",
    img: "https://pitstopslv.ru/images/products/21.jpg",
  },
  22: {
    id: 22,
    title: "Шаурма с курицей Мини",
    cost: 128,
    description:
      "Лаваш(на выбор), куриная грудка обжаренная в угольной печи, Фирменный белый соус, Фирменный красный соус, салат из огурца и помидора, репчатый лук,  капуста.",
    type: "Шаурма",
    img: "https://pitstopslv.ru/images/products/22.jpg",
    properties: {
      1: {
        name: "сырный (230г)",
        cost: "128",
        weight: "230",
      },
      2: {
        name: "классический (430г)",
        cost: "128",
        weight: "230",
      },
      3: {
        name: "сырный (430г)",
        cost: "168",
        weight: "430",
      },
      4: {
        name: "классический (430г)",
        cost: "168",
        weight: "430",
      },
    },
  },
  23: {
    id: 23,
    title: "Шаурма со свининой Мини",
    cost: 145,
    description:
      "Лаваш(на выбор), свинина обжаренная на угольной печи, Фирменный белый соус, Фирменный красный соус, салат из огурца и помидора, репчатый лук, капуста",
    type: "Шаурма",
    img: "https://pitstopslv.ru/images/products/23.jpg",
    properties: {
      1: {
        name: "сырный (230г)",
        cost: "145",
        weight: "230",
      },
      2: {
        name: "классический (430г)",
        cost: "145",
        weight: "230",
      },
      3: {
        name: "сырный (430г)",
        cost: "205",
        weight: "430",
      },
      4: {
        name: "классический (430г)",
        cost: "205",
        weight: "430",
      },
    },
  },
  24: {
    id: 24,
    title: "Экспресс Обед со Свининой",
    cost: 290,
    description:
      "Стейк из свиной шеи обжаренной на угольной печи, картофельными дольками, Соус Тар-Тар, Соус BBQ, маринованный репчатый лук, 2 кусочка хлеба. Обед упакован в ланч - бокс, подается с приборами",
    weight: "150\\150\\30\\50\\50\\70 - 500",
    type: "Экспресс обед",
    img: "https://pitstopslv.ru/images/products/24.jpg",
  },
  25: {
    id: 25,
    title: "Хот-Дог",
    cost: 79,
    description:
      "Добавки : корнишоны - 10 рублей. Лук фри - 10 рублей. (по телефону)",
    type: "Хот Дог",
    img: "https://pitstopslv.ru/images/products/25.jpg",
    properties: {
      1: {
        name: "1 сосиска",
        cost: "79",
        weight: "",
      },
      2: {
        name: "2 сосиски",
        cost: "95",
        weight: "",
      },
      3: {
        name: "3 сосиски",
        cost: "110",
        weight: "",
      },
    },
  },
  26: {
    id: 26,
    title: "Пицца Мясная 30 см",
    cost: 455,
    description:
      "Моцарелла, ветчина, сосиски рубленные, бекон, томаты, пармезан.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/26.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "325",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "455",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "640",
        weight: "1300",
      },
    },
  },
  27: {
    id: 27,
    title: "Пицца Ветчина с грибами 30 см",
    cost: 420,
    description:
      "Пицца соус, моцарелла, ветчина , томаты, шампиньоны, красный лук, специи.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/27.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "295",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "420",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "610",
        weight: "1000",
      },
    },
  },
  28: {
    id: 28,
    title: "Пицца Гавайская 30 см",
    cost: 445,
    description:
      "соус пицца, моцарелла, ветчина, куриная грудка копченая, ананасы,сыр пармезан, соус BBQ, базилик",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/28.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "315",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "445",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "620",
        weight: "1100",
      },
    },
  },
  29: {
    id: 29,
    title: "Пицца Четыре сыра 30 см",
    cost: 450,
    description:
      "Соус блю чиз, моцарелла, сыр гауда, сливочный сыр, пармезан, чеснок.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/29.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "325",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "450",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "615",
        weight: "1200",
      },
    },
  },
  30: {
    id: 30,
    title: "Пицца Деревенская 30 см",
    cost: 455,
    description:
      "белый соус, сыр моцарелла,куриное филе, ветчина,томаты, шампиньоны, пармезан.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/30.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "325",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "455",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "640",
        weight: "1300",
      },
    },
  },
  31: {
    id: 31,
    title: "Пицца Карбонара 30 см",
    cost: 440,
    description: "моцарелла, бекон, томаты, пармезан, яйцо .",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/31.jpg",
    chasto: true,
    properties: {
      1: {
        name: "маленькая",
        cost: "305",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "440",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "610",
        weight: "1100",
      },
    },
  },
  32: {
    id: 32,
    title: "Пицца Мини",
    cost: 69,
    description:
      "Колбаса полукопченая,томаты,сыр деревенский,красный соус,майонез,масло чесночное.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/32.jpg",
  },
  33: {
    id: 33,
    title: "Морсы и лимонад.",
    cost: 55,
    description: "Натуральные домашние морсы и лимонад.",
    type: "Напитки",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/33.jpg",
    properties: {
      1: {
        name: "облепиха",
        cost: "55",
        weight: "330",
      },
      2: {
        name: "смородина",
        cost: "55",
        weight: "330",
      },
      3: {
        name: "клюква",
        cost: "55",
        weight: "330",
      },
      4: {
        name: "лимонад",
        cost: "55",
        weight: "330",
      },
    },
  },
  34: {
    id: 34,
    title: "Картофель ФРИ",
    cost: 90,
    description: "90 гр - 90 руб., 150 гр - 125 рублей",
    type: "Закуски",
    img: "https://pitstopslv.ru/images/products/34.jpg",
    properties: {
      1: {
        name: "90гр",
        cost: "90",
        weight: "90",
      },
      2: {
        name: "150гр",
        cost: "125",
        weight: "150",
      },
    },
  },
  35: {
    id: 35,
    title: "Картофель по-деревенски",
    description: "85 гр - 80 рублей.\n135 гр - 110 рублей.",
    type: "Закуски",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/35.jpg",
    properties: {
      1: {
        name: "85гр",
        cost: "80",
        weight: "85",
      },
      2: {
        name: "135гр",
        cost: "110",
        weight: "135",
      },
    },
  },
  36: {
    id: 36,
    title: "Крылья BBQ",
    cost: 400,
    description: "Пикантные и  ароматные крылышки  BBQ",
    weight: 1000,
    type: "Курица гриль",
    img: "https://pitstopslv.ru/images/products/36.jpg",
  },
  37: {
    id: 37,
    title: "Курица ГРИЛЬ",
    cost: 380,
    description: "Сочная курочка гриль. Жарится по половике",
    weight: 1000,
    type: "Курица гриль",
    img: "https://pitstopslv.ru/images/products/37.jpg",
  },
  38: {
    id: 38,
    title: "Соусы  Порционные",
    cost: 35,
    description: "Соусы в ассортименте ",
    type: "Закуски",
    img: "https://pitstopslv.ru/images/products/38.jpg",
    properties: {
      1: {
        name: "томатный",
        cost: "35",
        weight: "",
      },
      2: {
        name: "чесночный",
        cost: "35",
        weight: "",
      },
      3: {
        name: "барбекю",
        cost: "35",
        weight: "",
      },
      4: {
        name: "сырный",
        cost: "35",
        weight: "",
      },
    },
  },
  39: {
    id: 39,
    title: "Бургер РОКФОР",
    cost: 220,
    description:
      "(Белая булка,соус блю-чиз,салат айсберг,лук карамелизированный, говяжья котлета, сыр чеддер, бекон,томаты,соус цахтон)\n",
    weight: 290,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/39.jpg",
  },
  40: {
    id: 40,
    title: "Бургер ГОРЯЧАЯ ГОЛОВА",
    cost: 220,
    description:
      "(Булка белая, соус тартар, лук карамелизированный, салат айсберг, котлета говяжья, сыр гауда, томаты, перец халапеньо, соус BBQ)\nВес: 290 грамм",
    weight: 290,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/40.jpg",
  },
  41: {
    id: 41,
    title: "Бургер С КРЕВЕТКОЙ",
    cost: 265,
    description:
      "(Булка белая, соус фирменный икорный, салат Айсберг, креветки  тигровые, бекон, соус красный)\nВес: 210 грамм",
    weight: 210,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/41.jpg",
  },
  42: {
    id: 42,
    title: "Бургер ПЕРВУШКИН",
    cost: 320,
    description:
      "(Булка белая,соус медово-горчичный, салат айсберг,двойная говяжья котлета,сыр чеддер,томаты,бекон,соус BBQ,перец холопеньо,соус белый)\n440 грамм",
    weight: 440,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/42.jpg",
  },
  43: {
    id: 43,
    title: "Бургер ПЬЯНЫЙ ПЯТАЧОК",
    cost: 320,
    description:
      "(Белая булка,салат айсберг,соус пивной,красный  лук карамелизированный ,сыр чеддер, томаты,бекон,двойная котлета из мраморной говядины,яйцо гриль,сырный соус)\nВес: 440 грамм",
    weight: 440,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/43.jpg",
  },
  44: {
    id: 44,
    title: "ЧИЗБУРГЕР",
    cost: 149,
    description:
      "соус BBQ,соус Тартар, салат айсберг ,красный лук, котлета (на выбор), помидор, сыр чеддер.",
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/44.jpg",
    properties: {
      1: {
        name: "куриная котлета",
        cost: "129",
        weight: "230",
      },
      2: {
        name: "говяжья котлета",
        cost: "149",
        weight: "230",
      },
    },
  },
  45: {
    id: 45,
    title: "Наггетсы",
    cost: 90,
    description: "Натуральное куриное филе в хрусте  Собственное производство.",
    type: "Закуски",
    img: "https://pitstopslv.ru/images/products/45.jpg",
    properties: {
      1: {
        name: "3шт.",
        cost: "90",
        weight: "",
      },
      2: {
        name: "6шт.",
        cost: "150",
        weight: "",
      },
      3: {
        name: "9шт.",
        cost: "199",
        weight: "",
      },
    },
  },
  46: {
    id: 46,
    title: "Бургер ПИТ-STOP",
    cost: 220,
    description:
      "(Белая булка, говяжья котлета на гриле,сыр Чеддер, салат айсберг, томаты, красный лук, соус тейсти)",
    weight: 270,
    type: "Бургеры",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/46.jpg",
  },
  47: {
    id: 47,
    title: "Бургер ПИТБУРГЕР",
    cost: 320,
    description:
      " Состав: белая булка, двойная котлета из мраморной говядины , сыр чеддер, бекон ,томаты ,айсберг, лук жаренный ,соус фирменный.",
    weight: 440,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/47.jpg",
  },
  48: {
    id: 48,
    title: "СТЕЙКБУРГЕР",
    cost: 290,
    description:
      "(Белая булка, яйцо, томат, стейк из свинины, бекон, салат Айсберг, лук, сыр чеддер,соус тартар и BBQ)",
    weight: 350,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/48.jpg",
  },
  49: {
    id: 49,
    title: "Хот-Дог с рубленой сосиской",
    cost: 100,
    description: "С одной сосиской-100 рублей.С двумя сосисками-115 рублей.",
    type: "Ход Дог",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/49.jpg",
    properties: {
      1: {
        name: "1 сосиска",
        cost: "100",
        weight: "500",
      },
      2: {
        name: "2 сосиски",
        cost: "115",
        weight: "500",
      },
    },
  },
  50: {
    id: 50,
    title: "Гамбургер",
    cost: 129,
    description:
      "Белая булка, айсберг, котлета говяжья, сыр чеддер,соус тартар.",
    weight: 160,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/50.jpg",
  },
  51: {
    id: 51,
    title: "Блинчик с варёной сгущенкой",
    cost: 35,
    weight: 100,
    type: "Блины с начинкой",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/51.jpg",
  },
  52: {
    id: 52,
    title: "Блинчик с бананом и шоколадом",
    cost: 37,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/52.jpg",
  },
  53: {
    id: 53,
    title: "Блинчик с клубничным конфитюром",
    cost: 35,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/53.jpg",
  },
  54: {
    id: 54,
    title: "Блинчик с конфитюром из киви",
    cost: 35,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/54.jpg",
  },
  55: {
    id: 55,
    title: "Блинчик с творогом и изюмом",
    cost: 38,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/55.jpg",
  },
  56: {
    id: 56,
    title: "Блинчик с ветчиной и сыром",
    cost: 43,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/56.jpg",
  },
  57: {
    id: 57,
    title: "Блинчик с фаршем",
    cost: 45,
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/57.jpg",
  },
  58: {
    id: 58,
    title: "Пицца Курица с грибами",
    cost: 440,
    description:
      "Состав: соус пицца, моцарелла , вешенки, шампиньоны , чери, кукуруза, курица, соус песто, пармезан",
    weight: 800,
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/58.jpg",
  },
  59: {
    id: 59,
    title: "Хачапури по-Аджарски",
    cost: 295,
    description: "Состав: сыр сулугуни, сыр адыгейский ,желток.",
    weight: 340,
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/59.jpg",
  },
  60: {
    id: 60,
    title: "Блинчик",
    cost: 22,
    description: "Блинчик без начинки",
    weight: 60,
    type: "Блины с начинкой",
    chasto: true,
    img: "https://pitstopslv.ru/images/products/60.jpg",
  },
  61: {
    id: 61,
    title: "PEPPER MIXI",
    cost: 220,
    description:
      " белая булка, соус тартар, лук красный , котлета говяжья, салат айсберг , сыр чеддер, бекон , томаты свежие , соус перечный",
    weight: 310,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/61.jpg",
  },
  62: {
    id: 62,
    title: "PEPPER KARI",
    cost: 220,
    description:
      "белая булка, соус кари, лук красный , салат айсберг , сыр чеддер, томаты, котлета говяжья, бекон, соус перечный",
    weight: 310,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/62.jpg",
  },
  63: {
    id: 63,
    title: "Экспресс-обед с куриной грудкой на гриле",
    cost: 220,
    description:
      "Куриная грудка обжаренная  на угольной печи, картофельные дольки, Соус Тар-Тар, Соус BBQ, маринованный репчатый лук, 2 кусочка хлеба. \nОбед упакован в ланч - бокс, подается с приборами",
    weight: "150\\150\\30\\50\\50\\70 - 500",
    type: "Экспресс обед",
    img: "https://pitstopslv.ru/images/products/63.jpg",
  },
  64: {
    id: 64,
    title: "Пельмени вареные",
    cost: 120,
    description: "Пельмени вареные",
    weight: 170,
    type: "Пельмени",
    img: "https://pitstopslv.ru/images/products/64.jpg",
  },
  65: {
    id: 65,
    title: "Пельмени под сыром",
    cost: 120,
    description: "Пельмени запеченные под сыром",
    weight: 170,
    type: "Пельмени",
    img: "https://pitstopslv.ru/images/products/65.jpg",
  },
  66: {
    id: 66,
    title: "Пельмени жаренные",
    cost: 120,
    description: "Жаренные пельмени",
    weight: 170,
    type: "Пельмени",
    img: "https://pitstopslv.ru/images/products/66.jpg",
  },
  67: {
    id: 67,
    title: "Пицца Охотничья 30 см",
    cost: 445,
    description:
      "Сыр моцарелла, томаты, говядина копчёная, колбаски охотничьи, пармезан, петрушка, перец болгарский, соус Цезарь, красный лук.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/67.jpg",
    properties: {
      1: {
        name: "маленькая",
        cost: "320",
        weight: "400",
      },
      2: {
        name: "средняя",
        cost: "445",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "640",
        weight: "1300",
      },
    },
  },
  68: {
    id: 68,
    title: "Пицца Пепперони 30 см",
    cost: 445,
    description: "Сыр моцарелла, пепперони,соус.",
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/68.jpg",
    chasto: true,
    properties: {
      1: {
        name: "маленькая",
        cost: "320",
        weight: "380",
      },
      2: {
        name: "средняя",
        cost: "445",
        weight: "700",
      },
      3: {
        name: "большая",
        cost: "610",
        weight: "1000",
      },
    },
  },
  69: {
    id: 69,
    title: "Пицца Римская",
    cost: 450,
    description:
      " Сыр Сулугуни, адыгейский сыр, бекон, моцарелла, черри,  корнишоны, пармезан.\n900 гр ",
    weight: 900,
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/69.jpg",
  },
  70: {
    id: 70,
    title: "Бургер Греческий",
    cost: 220,
    description:
      "Состав: Булочка белая, перец болгарский, котлета из мраморной говядины, бекон, сыр Гауда, лук фиолетовый маринованный, соус зеленый, соус перечный.",
    weight: 280,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/70.jpg",
  },
  71: {
    id: 71,
    title: "Бургер Мясной Удар",
    cost: 220,
    description:
      "Состав: Булочка белая, айсберг, жареные шампиньоны, котлета из мраморной говядины, сыр Гауда, томаты, лук жареный, соус мясной.",
    weight: 300,
    type: "Бургеры",
    img: "https://pitstopslv.ru/images/products/71.jpg",
  },
  72: {
    id: 72,
    title: "Хот-Дог с охотничьей сосиской",
    cost: 120,
    description:
      "Две охотничьи сосиски, с салатом на выбор: капустный,морковча. Кетчуп,майонез,горчица по желанию.",
    type: "Ход Дог",
    img: "https://pitstopslv.ru/images/products/72.jpg",
  },
  73: {
    id: 73,
    title: "Ребра свиные BBQ",
    cost: 220,
    description: " Свиные ребра BBQ с овощами.",
    weight: 340,
    type: "Экспресс обед",
    img: "https://pitstopslv.ru/images/products/73.jpg",
  },
  74: {
    id: 74,
    title: "Салат Коул-слоу",
    cost: 32,
    description: "Морковка, Капуста с добавлением специй и майонеза",
    weight: 100,
    type: "Салаты",
    img: "https://pitstopslv.ru/images/products/74.jpg",
  },
  75: {
    id: 75,
    title: "Пицца Чикен Чиз",
    cost: 445,
    description: "Помидорки чери,курица,бекон, сырный соус.",
    weight: 700,
    type: "Пицца",
    img: "https://pitstopslv.ru/images/products/75.jpg",
  },
  76: {
    id: 76,
    title: "Блинчик с курицей и огурцом",
    cost: 45,
    description:
      "Состав: Блинчик, жареное куриное филе, огурец, фирменный сосус",
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/76.jpg",
  },
  77: {
    id: 77,
    title: "Блинчик с грибами( Вёшенки)",
    cost: 32,
    description: "Состав: Блинчик, Жаренные грибы Вёшенки, чеснок.",
    weight: 100,
    type: "Блины с начинкой",
    img: "https://pitstopslv.ru/images/products/77.jpg",
  },
  78: {
    id: 78,
    title: "Самса с курицей",
    cost: 65,
    description:
      "Самса с кусочками рубленного куриного филе, луком, испеченная в слоеном тесте с кунжутом",
    weight: 180,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/78.jpg",
  },
  79: {
    id: 79,
    title: "Пирожок с капустой",
    cost: 30,
    description:
      "Состав: Тесто дрожжевое, тушеная капуста с добавлением морковки",
    weight: 160,
    type: "Печеная продукция",
    img: "https://pitstopslv.ru/images/products/79.jpg",
  },
  80: {
    id: 80,
    title: "Сэндвич с ветчиной и сыром",
    cost: 140,
    description:
      "Состав: Хлеб тостовый, соус тартар, салат айсберг, ветчина, томаты, огурцы",
    weight: 200,
    chasto: true,
    type: "Сэндвичи",
    img: "https://pitstopslv.ru/images/products/80.jpg",
  },
  81: {
    id: 81,
    title: "Пончик",
    cost: 18,
    description: "Пончик сладкий",
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/81.jpg",
  },
  82: {
    id: 82,
    title: "Чебурек с курицей",
    cost: 45,
    description: "с куриным фаршем",
    type: "Жаренная Продукция",
    img: "https://pitstopslv.ru/images/products/82.jpg",
  },
  83: {
    id: 83,
    title: "Сэндвич с лососем",
    cost: 210,
    description:
      "Состав: Хлеб тостовый, соус тартар, салат айсберг, лосось с\\с, томаты, огурцы",
    type: "Сэндвичи",
    img: "https://pitstopslv.ru/images/products/83.jpg",
  },
  84: {
    id: 84,
    title: "Сэндвич с курицей",
    cost: 140,
    description:
      "Состав: Хлеб тостовый, соус тартар, салат айсберг, курица, томаты, огурцы",
    type: "Сэндвичи",
    img: "https://pitstopslv.ru/images/products/84.jpg",
  },
};

const base = [];
/*fetch("http://pitstopslv.ru/json.json", {
  method: "GET", // POST, PUT, DELETE, etc.
  headers: {
    "Content-Type": "text/json;charset=UTF-8",
  },
  mode: "no-cors",
})
  .then((response) => response.json())
  .then((datas) => console.log(datas))
  .catch((err) => console.log(err));*/

Object.keys(data).forEach((element) => {
  base.push(data[element]);
});
export { base } ;